### ISSUE TITLE
Blender 4.0 compatibility

### ISSUE THREAD

**Issue by Mustard2** [theoldben/BlenderNormalGroups#15]
Hi!

The add-on doesn't work with Blender 4.0 because they changed some API functions to create node sockets.

I think we just need to change the input part at line 

https://github.com/theoldben/BlenderNormalGroups/blob/4a466902ac06ef88ba74c65883ad7a4d5c39cea0/normal_map_to_group.py#L150

with

```
    # Input
    input = group.interface.new_socket("Strength", in_out='INPUT', socket_type='NodeSocketFloat')
    input.default_value = 1.0
    input.min_value = 0.0
    input.max_value = 1.0
    input = group.interface.new_socket("Color", in_out='INPUT', socket_type='NodeSocketColor')
    input.default_value = ((0.5, 0.5, 1.0, 1.0))

    # Output
    group.interface.new_socket("Normal", in_out='OUTPUT', socket_type='NodeSocketVector')
```

No other changes needed as of the current Blender 4.0 beta version.

**Comment by Ogyly** [comment]
now it works fine again. thank you.

**Comment by theoldben** [comment]
Made the changes, thank you for your contribution, as always!
