### ISSUE TITLE
Thank you so much for updating this to 4.0

### ISSUE THREAD

**Issue by blender-tv-studio** [theoldben/BlenderNormalGroups#17]
n/a  Ohh now that we have GPT you could always just throw this whole thing in there and see how further it could optimize normal maps that'd be a good experiment actually I think I'm gonna do that you let me use your code so if I don't hear back from you then I'll do that pretty soon and see what I come up with and if I come up with anything better then I'll send it to you..

**Comment by blender-tv-studio** [comment]
as thank you... For helping my add on in its early stages.... here's a free copy of my add on good forever I'm never gonna put checks on the update process so it has all my work that I've done since then ...it's now the biggest blender addon in the entire world code wise...1.5GB uncompressed... Must mention code wise.....we all know how big transportation is... It's completely modular you could disable anything you don't want and only keep what you truly wanna keep it's truly like a hundred add-ons in one...Regards!

**Comment by theoldben** [comment]
keep reaching for that rainbow, brother!

**Comment by blender-tv-studio** [comment]
Thanks my friend!!!
