### ISSUE TITLE
3.6 errors

### ISSUE THREAD

**Issue by marquismiller** [theoldben/BlenderNormalGroups#18]
![error](https://github.com/theoldben/BlenderNormalGroups/assets/90892903/f6951f4b-680f-442a-884e-ac782a5fec19)

Clicked custom and got this error. Using Blender 3.6.

**Comment by theoldben** [comment]
Are you using the version from the 4.0 fork by any chance?

**Comment by marquismiller** [comment]
I'm cloning it using Github Desktop the master branch.
THe other branches I see are: "2.8 to 3.0" and "4.0" but nothing in-between.

**Comment by theoldben** [comment]
the naming is inaccurate, but you need the earlier branch, the 4.0 branch is for blender 4.0 and above.

**Comment by marquismiller** [comment]
Here's the error I recieved using 2.8 - 3.0 on 3.6..
![erroragainnormal](https://github.com/theoldben/BlenderNormalGroups/assets/90892903/7a366839-f799-41b9-8b02-87b60bdbf643)

Here's the outcome when in use 
https://github.com/theoldben/BlenderNormalGroups/assets/90892903/cfd2ffeb-649f-48b9-b073-165d4bdcb7e0
The setup breaks

**Comment by theoldben** [comment]
Can you share the file that causes the error? If not, could you try running the afdon on a blank file with your blender install that only has one simple object with normals?
