### ISSUE TITLE
Using Blender 4.1 click custom and get error with your  4.0 and after  release

### ISSUE THREAD

**Issue by aknittel1** [theoldben/BlenderNormalGroups#19]
IndexError: bpy_prop_collection[index]: index 2 out of range, size 2
Error: Python: Traceback (most recent call last):
  File "C:\Users\aknit\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\normal_map_to_group.py", line 128, in execute
    set_custom(getattr(mat.node_tree, 'nodes', []))
  File "C:\Users\aknit\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\normal_map_to_group.py", line 112, in set_custom
    uvNode.id_data.links.new(uvNode.outputs['UV'], new.inputs[2])
                                                   ~~~~~~~~~~^^^
IndexError: bpy_prop_collection[index]: index 2 out of range, size 2

**Comment by theoldben** [comment]
Looks like there has been a change to the UV node in that version.

I will take a look at it.

**Comment by theoldben** [comment]
Ok, you can fix is by just replacing the 2 in `new.inputs[2]` with `"Color"`, so the new line would read:
`uvNode.id_data.links.new(uvNode.outputs['UV'], new.inputs["Color"])`
I will post the fix in a minute.

**Comment by aknittel1** [comment]
Thanks that did the trick! All good.

**Comment by aknittel1** [comment]
Spoke to fast. You have an issue with the UV node feeding the optimized normal map sticking around when reverting to the non optimized normal map. It's breaking normal renders. Here's the shader from my original file reset to non-optimized:

![image](https://github.com/theoldben/BlenderNormalGroups/assets/22087392/3d583d8c-da68-46d8-a78c-5cc18a795c95)

WHen I click "custom" I get an additional UV node feeding the optimized normal node, and the texture node is disconnected:

![image](https://github.com/theoldben/BlenderNormalGroups/assets/22087392/f3feafdd-111a-42c6-8d06-df1ba8056280)

When I click back to "Normal", the optimized normal map node reverts to non-optimized without a UV property, but the UV node you added is not removed, and the texture node is not reconnected:

![image](https://github.com/theoldben/BlenderNormalGroups/assets/22087392/feca17c2-d36a-49c7-b5e4-d4edf449e1ca)

**Comment by aknittel1** [comment]
BTW, In Blender 3.6 there is NO UV node in between the texture node and the normal map. Don't know why you have added one in the 4.1 version of the script in the first place. I know it's related to my reporting an error in the script, but dont understand the reason you decided to add a UV node.

**Comment by theoldben** [comment]
I added a line that Mustard put in last time. The UV Maps are stored for backup. In case of multiple maps, they would get lost, which might result in incorrect texture mapping. Let me know if that fixes your issue.

**Comment by aknittel1** [comment]
That fixed the issue. Now reverting to Normal does return the node tree back to its original.

I can barely notice the difference in performance now with 4.1 re-posing characters. Have you noticed a general increase in animation performance in the EEVEE viewport despite the shader optimization?

**Comment by aknittel1** [comment]
I take that back. I have a cat with fur and if I zoom the viewport up close and move the entire rig around, it's markedly smoother when i'm using the optimized node tree. If EEVEE is ever optimized in future versions (EEVEE Next?) maybe the need for the addon will go away. Who knows? Thanks very much!

**Comment by theoldben** [comment]
It would of course be great if there was no need for the addon any more, but changing EEVEE to not evaluate the normal maps on every frame is a major undertaking, so in a perverse twist of fate, making the addon actually decreased the chances of that change occuring, since this workaround exists now.
Who knows, it might still happen. And maybe sooner than we dare to dream.
