### ISSUE TITLE
Can we create a backport branch of this for 2.79x?

### ISSUE THREAD

**Issue by BluePrintRandom** [theoldben/BlenderNormalGroups#3]
people use 2.79x still and I think this would be good to backport 
for bge users especially 

do you think all the nodes exist in 2.79 to pull this off?

**Comment by theoldben** [comment]
I am not sure why you would need to backport it, since it is a performance enhancer for the eevee-engine, and that simply did not exist in 2.79. That said, it might still work, while there were some changes to the node system, most of the internals are still intact.

**Comment by BluePrintRandom** [comment]
the performance boost here comes from calculating the tangents on the GPU instead of the cpu I believe

this apparently makes animated actors in upbge 0.3.0 / (eevee) quite a bit faster 
I was just wondering if the approach could help people in upbge legacy / bge
