### ISSUE TITLE
Install Not Working

### ISSUE THREAD

**Issue by vranimeted** [theoldben/BlenderNormalGroups#5]
I've tried installing the addon on multiple different installs of Blender, the latest being a self-contained 3.0.1 install that I've tried on 2 different computers and though I get the install successful console message, I never see the custom/normal buttons on the let sidebar of the shader window under links cut.
Here is a copy of the 3.0.1 self-contained version I ran the last test with.
https://we.tl/t-OagqClZgNJ

**Comment by 9wow** [comment]
same here v3.1.0

**Comment by vranimeted** [comment]
Not sure how it was resolved, but after reinstalling my OS and installing this addon first I was able to get it working (3.1.0)

**Comment by GGorchitsa** [comment]
3.3.1, master zip wouldn't install, but downloading and installing just the .py file worked.
