### ISSUE TITLE
I'm talking with the makers of 2 major blender addons about using your normal maps in their code is this possible ....

### ISSUE THREAD

**Issue by blender-tv-studio** [theoldben/BlenderNormalGroups#9]
One is "extreme PBR" it's A PBR material pack kinda thing for blender it's the biggest 1 they have these very specialized node groups called Nexus nodes ...I wondered if they could use your optimized normal map code in their code as an addition to the group nodes set up they have... And  And then the biggest PBR material addon for blender.. Would be optimized with your code 

the guy that wrote extreme PBR is making a new super secret add on ...in it he is making a list of top blender addons in a panel and is add on preferences

  You can start selling this for 10 bucks a pop on blender market and maybe I can convince this guy to add you to that list of top blender addons... Then this would really advertise this code and get this out to the millions of blender users because this is vital information they should all have You would be a hero for how much performance you've given to blender.... And if you do put this add on up for sale like I suggest you can start making some money...

 Also if you don't even care about the fame or anything if we could just use your code you know I'll be throwing recognition out all over the place on my tutorials... And commercials I'm gonna make I'm coming up to a lot of genius ideas

**Comment by theoldben** [comment]
Ok, I have to say this again, it seems this is not a well-known fact, but i only had very minor part in making this addon, it was done with the help of two of my associates, my function is only maintenance for as long as EEVEE requires it. 

The blender community is about being open source, so selling this addon has never been an option.

If you want to use the addon to incorporate into yours, feel free to do so, just please make sure to credit my friends for it and best of luck with your addon.

**Comment by blender-tv-studio** [comment]
Sweet corn!!... Thank you so much we will totally give credit...and A
PARADE!!
